### ISSUE TITLE
Breaking changes detection is not compliant with the specification

### ISSUE THREAD

**Issue by gotson** [caarlos0/svu#106]
According to the conventional commit specification:

> The units of information that make up Conventional Commits MUST NOT be treated as case sensitive by implementors, with the exception of BREAKING CHANGE which MUST be uppercase.
BREAKING-CHANGE MUST be synonymous with BREAKING CHANGE, when used as a token in a footer.

Looking at the code it seems the regex is case insensitive, and does not match the token containing a dash.

**Comment by caarlos0** [comment]
Ahh good catch!
