### ISSUE TITLE
ability to provide custom commit types

### ISSUE THREAD

**Issue by gotson** [caarlos0/svu#107]
Would you consider supporting custom commit types ?

For example one could consider commits of type let's say `perf`, that would result in a PATCH bump.

**Comment by caarlos0** [comment]
Right now any commit mentioning "BREAKING CHANGE" results in a major, any commit with the feat prefix results in a minor, and everything else results in a patch increment...

**Comment by gotson** [comment]
> I would probably rather keep it that way tbh

That's why I am asking, it may be out of scope. Conventional commit spec is vague on that point, it allows other commit types, but doesn't prescribe how they should be handled.

**Comment by caarlos0** [comment]
yeah, thats why we handle them all as patch increments...

**Comment by gotson** [comment]
Feel free to close this if you have no plans to add this feature :)

**Comment by prewk** [comment]
>everything else results in a patch increment

The readme says `chore` doesn't bump at all?
