### ISSUE TITLE
Need to use svu as a go library

### ISSUE THREAD

**Issue by alita1991** [caarlos0/svu#123]
Hi,

I have a use case, where I need to import and use an available go library that can do automatic version management. I explored a couple of options already and I decided to use svu.

The problems that I have encountered so far are the followings:

- git external dependency is used, instead of go-git (go implementation of git)
- no available logic to generate a prerelease automatically
- unable to import the library in my project (most of the methods are in the internal package)

Is there a chance to have any of those implemented in the near future? I'm open to contributing as well

Thanks

**Comment by caarlos0** [comment]
hi, no, no plans.

**Comment by ahaasler** [comment]
Hi, I have a similar requirement for using `svu` as a library instead of a binary. Would you be open to a pull request that exposes the main commands of the CLI to be used programmatically?

**Comment by smlx** [comment]
In case it is useful, I have a similar project which exposes a subset of `svu` functionality as a library: https://github.com/smlx/ccv

**Comment by caarlos0** [comment]
> Hi, I have a similar requirement for using `svu` as a library instead of a binary. Would you be open to a pull request that exposes the main commands of the CLI to be used programmatically?

yep, go for it

**Comment by caarlos0** [comment]
fixed by #126
