### ISSUE TITLE
Major == 0, no breaking changes

### ISSUE THREAD

**Issue by dvterry** [caarlos0/svu#153]
I am curious about [this decision](https://github.com/caarlos0/svu/blob/main/internal/svu/svu.go#L198). I assume there's a legitimate reason behind it, but it seems pretty prescriptive. With this I can't go from major version 0 to 1 with a breaking change. I am using svu in an automated release pipeline and this tiny bit of logic breaks my automation. Shouldn't this be behind a flag as an option rather than a defacto implementation? 

Can you explain the reasoning?

**Comment by caarlos0** [comment]
hey, yes, indeed that should probably be behind a flag
