### ISSUE TITLE
v2.1 regression on Windows

### ISSUE THREAD

**Issue by NathanBaulch** [caarlos0/svu#166]
PR #161 broke my release process on Windows. I'm not sure why but the paths returned from `os.Getwd()` and `git.Root()` do not match when running this tool via `go run` and a weird prefix is added to the pattern.

```shell
D:\Work\myproject> go run github.com/caarlos0/svu/v2@v2.0.1
v2.0.19
D:\Work\myproject> go run github.com/caarlos0/svu/v2@v2.1.0
svu: error: failed to get current tag for repo: no tags match 'D:\Work\myproject/*'
exit status 1
```

If I build a `svu.exe` from source and use that it works, however that doesn't work for my setup.

The only way I've found to work around this issue is by explicitly specifying the `pattern` and `prefix` flags.

```shell
D:\Work\myproject> go run github.com/caarlos0/svu/v2@v2.1.0 --pattern=* --prefix=v
v2.0.19
```

cc @aymanbagabas

**Comment by caarlos0** [comment]
related to #164 maybe? can you try `main`?

**Comment by NathanBaulch** [comment]
It does indeed @caarlos0, sorry about the dupe!
I incorrectly assumed when troubleshooting that running `@latest` would use the repo HEAD but of course it's only an alias for the latest release (v2.1.0).

```shell
D:\Work\myproject> go run github.com/caarlos0/svu/v2@latest
svu: error: failed to get current tag for repo: no tags match 'D:\Work\myproject/*'
exit status 1
D:\Work\myproject> go run github.com/caarlos0/svu/v2@6862035746d94f022421128a3e327746b21f835c
v2.0.19
```

Looking forward to v2.1.1.
