### ISSUE TITLE
v2.1 behavior change

### ISSUE THREAD

**Issue by NathanBaulch** [caarlos0/svu#168]
Thanks for the v2.1.1 release @caarlos0, that solved the Windows issue!

However there's still a behavior change in this version that's worth mentioning. I have a monorepo where all components are versioned in unison. Starting in v2.1 I can no longer get the current tagged version in scripts and Makefiles within sub-directories. Unless I explicitly specify the pattern and prefix arguments, #161 means `svu` will always assume I'm in a sub-package now.

I'm not sure what the best solution for this is, but IMO the new behavior feels overly opinionated/unexpected.

**Comment by mcinj** [comment]
> I'm not sure what the best solution for this is, but IMO the new behavior feels overly opinionated/unexpected.

@NathanBaulch, I agree. This feels like a change that should be rolled back given it modified existing functionality. Then a new switch/flag should be added that applies the #161 logic.

**Comment by caarlos0** [comment]
reverted the changes that caused this
