### ISSUE TITLE
"fix: " not incrementing patch version

### ISSUE THREAD

**Issue by cuotos** [caarlos0/svu#18]
I created an empty repo, added a README.md and tagged with v0.1.0

making a change and committing with the message `fix: fixed something`
```
* dfea6e8b - (7 seconds ago) (HEAD -> master) Cuotos - fix: fixed something 
* 1dc551c3 - (82 seconds ago) (tag: v0.1.0) Cuotos - readme 
```

```
$ svu
v0.1.0
```

I would expect this to be `v0.1.1`. calling `svu patch` correctly returns `v0.1.1`.
`fix!: message` also correctly increases the Major version

**Comment by caarlos0** [comment]
Oh, thanks for catching that. Fixing!

**Comment by cuotos** [comment]
just came back to drop a reference to where the problem was, but you've already fixed. Awesome work
