### ISSUE TITLE
Breaking changes via ! for other commit types

### ISSUE THREAD

**Issue by 56KBs** [caarlos0/svu#22]
Following the conventional commit standards you are able to define breaking versions by appending the type of commit with a `!`.

However, when doing this in-conjunction with any commit type other than `fix` or `feat` you are unable to get a major version bump to be generated.

It does appear this was implemented during v1.1.0's life: https://github.com/caarlos0/svu/commit/30580f2715dc12d0077f8ec40a5bc0d2211ec3a8
And then removed: https://github.com/caarlos0/svu/commit/add1a806ddf963cdaaeb2df058dcdf3c5aeba656

For example:

`chore!: A breaking chore` this should generate a major version bump

**Comment by caarlos0** [comment]
I had in my head that this was implemented already... 

thanks for reporting
