### ISSUE TITLE
Using gitmoji's instead of convential commits

### ISSUE THREAD

**Issue by srizzling** [caarlos0/svu#23]
## Introduction

I am heavily inspired of the simplicity of `svu` - that I would like to request a feature that would help my personal workflow - but I understand that adding a new feature like this may introduce complexity - and I'm happy to make a fork if thats the case.

The basic jist is if we have commits like:

✨ support customer withdrawls
🐛 disallow negative bank balance withdrawls

I would like svu to create a semantic release based on the git log similar to how it is doing it for conventional commits such as fix, feat etc.

gitmoji recently assigned major, minor, patch to each emoji in this PR: https://github.com/carloscuesta/gitmoji/pull/692

FYi - I understand if you think this complicates svu - so I'm happy to create.. a heavily inspired project based on svu (with due credit as per the LICENSE)

**Comment by caarlos0** [comment]
I would be happy to review a PR adding it :)
