### ISSUE TITLE
Provide a Docker image

### ISSUE THREAD

**Issue by bmwinstead** [caarlos0/svu#28]
I almost just PR'd this since I think it would be trivial, but better to ask first. Can we publish a docker image for this tool? Assuming the answer is yes, would it then just be sufficient to include https://github.com/caarlos0/.goreleaserfiles/blob/main/docker.yml in the yaml file?

**Comment by caarlos0** [comment]
yup, that should do the trick :) 

thanks!

**Comment by cabrinha** [comment]
I opened the PR.

**Comment by caarlos0** [comment]
closed in https://github.com/caarlos0/svu/commit/cd55ecedba865a2dd85a32a9e746a68918828d5c
