### ISSUE TITLE
Initial version

### ISSUE THREAD

**Issue by rbuckland** [caarlos0/svu#29]
Given a repo that has no tags (yet), `svu` does not seem to be able to derive a version (`0.1.0 or 1.0.0` for example)
Is this something I am missing in the `--help` 
or is it a "feature request" ?

**Comment by caarlos0** [comment]
feature request I think...

**Comment by rockandska** [comment]
Would be neat.

Any PR in preparation @drewstinnett ?

**Comment by drewstinnett** [comment]
Perhaps! Got distracted after trying this out haha...PR submitted though...

**Comment by caarlos0** [comment]
merged, will clsoe
