### ISSUE TITLE
If the last tagged commit has multiple tags, svu should increment from the highest of those tags

### ISSUE THREAD

**Issue by abayer** [caarlos0/svu#37]
My release logic has blown up a few times and resulted in two svu-created tags going on the same commit, not necessarily with the "highest" tag being applied most recently. I'm not sure how that's happening, but hey, such is life. It'd be great if `svu patch` was able to handle these cases in such a way that the highest semver of all tags on the most recently tagged commit was used.

Here's an example of the scenario - a commit somehow ended up with both `v1.0.34` and `v1.0.35`. `v1.0.35` was applied before `v1.0.34`, so `svu patch` always returns `v1.0.35` for the next version, getting my automation stuck in an eternal loop of trying to create `v1.0.35`, but it already exists, etc.

I would've opened a PR for this if I could figure out a fix, but I haven't managed that yet. =)

**Comment by fatih** [comment]
We just hit the same problem. We had multiple tags pointing to the same ref. It broke our release pipeline because it doesn't pick up the largest tag.

**Comment by caarlos0** [comment]
can you verify if https://github.com/caarlos0/svu/pull/40 on your repos?

**Comment by fatih** [comment]
@caarlos0 thank you for this fix. I checked out your PR and tested in one of my test repositories:

```
$ git show-ref -s v1.0.0
4b5f9b13ec4afe8f81011b8580e165f1fcb0b139
$ git show-ref -s v1.1.0
4b5f9b13ec4afe8f81011b8580e165f1fcb0b139
$ svu minor
v1.2.0
```

I had two tags pointing to the same ref and  `svu` was able to pick up the largest one.

**Comment by caarlos0** [comment]
just released https://github.com/caarlos0/svu/releases/tag/v1.7.0
