### ISSUE TITLE
FR: Throw an error if "next" do not change

### ISSUE THREAD

**Issue by rockandska** [caarlos0/svu#42]
Hi,

The actual behavior is to print the last tag when asking `next` version even if there is no conventional commit who trigger a version bump.
Would be great to throw an error if there is no possibility to bump the version.

Regards,

**Comment by rockandska** [comment]
In fact, print nothing will be better than throwing an error

**Comment by gotson** [comment]
Seems opinionated, I prefer to compare the output of current and next to determine whether the version changes.

**Comment by caarlos0** [comment]
agree with @gotson, closing
