### ISSUE TITLE
git tag --sort=version:refname

### ISSUE THREAD

**Issue by blacktop** [caarlos0/svu#48]
I have no idea why this JUST started happening on my NEW Mac, but I did a fresh clone and now it is pulling the wrong "current" tag.  

This is because I used to try and follow the old `docker` style semver where it was based on the date, but like them decided that wasn't a good way to do it and switch back to traditional semver, but NOW my old tags (which are higher numbers due to the year) are being chosen instead of the real current tag?

I bet what is really happening is I was using an older version of svu and updated to latest on the NEW Mac and that's why?  Is there any way for you to get the versions based on "added date" or "commit date" ? instead of sorting by semver?

Thanks for a great tool.

**Comment by zhilyaev** [comment]
🤔 `git tag -l --sort=creatordate`

**Comment by blacktop** [comment]
❤️
