### ISSUE TITLE
[bug] svu next without "V"

### ISSUE THREAD

**Issue by zhilyaev** [caarlos0/svu#51]
```
$ git tag -l '[0-9]*' --sort=refname
7.11.4
7.12.0
7.14.0
7.15.0
$ echo $(svu next --strip-prefix)
7.14.0
```

**Comment by zhilyaev** [comment]
@caarlos0, can you give me some summary?

**Comment by caarlos0** [comment]
you didn't explain anything... I don't know what this issue was about

**Comment by zhilyaev** [comment]
Sorry my mistake. I try to explain.

ok, I reproduced it with new repository.
