### ISSUE TITLE
Once a suffix is appended to a tag, all later tags include the suffix

### ISSUE THREAD

**Issue by ghostsquad** [caarlos0/svu#53]
given a tag `v0.0.1`
if I run

```
git tag $(svu n --suffix=pr.000-d0a7d4c)
```

I get `v0.0.2-pr.000-d0a7d4c`

(where 000 is a pull request number, and d0a7d4c is a short git sha)

subsequent runs just end up taking the old suffix, and add a new suffix

```
svu n --suffix=pr.000-d0a7d4c
0.0.2-pr.000-d0a7d4c0.0.2-pr.000-d0a7d4c
```

I'm trying to figure out how to avoid the suffix duplication?
I think maybe I need a `--strip-suffix` ???

**Comment by caarlos0** [comment]
you can use `--no-metadata`
