### ISSUE TITLE
Creates a new tag ?

### ISSUE THREAD

**Issue by iangregsondev** [caarlos0/svu#7]
Hi,

Great little utility, i was hoping on using it with go-releaser :-)

It wasn't clear from the readme, but does this ONLY output the next semantic version based on conventional commits ?

Or does it create the tag ?

is there an option to create the tag ?

Thanks in advance

**Comment by caarlos0** [comment]
yes, it only outputs

you can use:

```sh
git tag `svu`
```

to do that for you :) 

I have it as an alias (`alias gtn='git tag $(svu)'`) and it works great :)

**Comment by caarlos0** [comment]
adding more info about this to the readme, thanks @iangregsondev :)
